### PR TITLE
cross platform NODE_ENV=production

### PR DESCRIPTION
**Pull request by thisconnect**
(https://github.com/vuejs/vue-loader-example/issues/22)

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks, but it doesn't seem to work for me on OS X. Maybe use [this](https://github.com/kentcdodds/cross-env)?

**Comment by thisconnect** [comment]
You a right, it is not minified…

**Comment by thisconnect** [comment]
`cross-env` looks ok, adding a second script for win builds would work too, something like `"build_windows": "set NODE_ENV=production&&webpack… `. Do you prefer `cross-env`?

**Comment by yyx990803** [comment]
I think just add note in the README telling windows users to change the build script would be fine. This repo is just an example, and people should expect to change the config for their needs.

**Comment by thisconnect** [comment]
going to close this for now

**Pull request closed without merging**
